easy_admin:
    entities:
        - App\Entity\Batiment
        - App\Entity\Emplacement
        - App\Entity\Fabricant
        - App\Entity\Local
        - App\Entity\Logiciel
        - App\Entity\Materiel
        - App\Entity\MaterielLogiciel
        - App\Entity\MaterielPieceRechange
        - App\Entity\MethodeSauvegarde
        - App\Entity\Modele
        - App\Entity\Sauvegarde
        - App\Entity\SupportSauvegarde
        - App\Entity\TypeMateriel
