vich_uploader:
    db_driver: orm

    mappings:
        image_modele:
            uri_prefix: /uploads/images/modeles
            upload_destination: '%kernel.project_dir%/public/uploads/images/modeles'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
